import ExcelJS from "exceljs";
import fs from "fs";
import path from "path";
import { logger } from "../utils/logger.js";
import { LOCATIONS, isPropertyInLocation } from "../config/locations.js";
import { config } from "../config/index.js";

/**
 * Simplified property shape for the HTML viewer.
 * Only the columns that are useful for display are included.
 */
export interface ViewerProperty {
  source: string;
  title: string;
  price: number | null;
  openingValue: number | null;
  minSaleValue: number | null;
  currentBid: number | null;
  location: string;
  district: string;
  municipality: string;
  parish: string;
  area: number | null;
  rooms: number | null;
  status: string;
  url: string;
  images: string[];
  latitude: number | null;
  longitude: number | null;
  auctionType: string;
  firstSeenAt: string;
  publishedAt: string;
}

/**
 * Reads a single sheet and converts each row into a ViewerProperty.
 * The column order matches PROPERTY_COLUMNS in excel.service.ts (A–W).
 */
async function readSheet(
  workbook: ExcelJS.Workbook,
  sheetName: string
): Promise<ViewerProperty[]> {
  const sheet = workbook.getWorksheet(sheetName);
  if (!sheet) return [];

  const rows: ViewerProperty[] = [];

  sheet.eachRow((row, rowNumber) => {
    if (rowNumber === 1) return; // skip header
    const v = row.values as any[];

    const images = v[16] ? String(v[16]).split(";").filter(Boolean) : [];

    rows.push({
      source: v[1] ?? "",
      title: v[2] ?? "",
      price: numOrNull(v[3]),
      openingValue: numOrNull(v[4]),
      minSaleValue: numOrNull(v[5]),
      currentBid: numOrNull(v[6]),
      location: v[8] ?? "",
      district: v[9] ?? "",
      municipality: v[10] ?? "",
      parish: v[11] ?? "",
      area: numOrNull(v[12]),
      rooms: numOrNull(v[13]),
      status: v[14] ?? "",
      url: v[15] ?? "",
      images,
      latitude: numOrNull(v[17]),
      longitude: numOrNull(v[18]),
      auctionType: v[24] ?? "",
      publishedAt: v[19] ?? "",
      firstSeenAt: v[20] ?? "",
    });
  });

  return rows;
}

/** Converts a cell value to a number or null. */
function numOrNull(val: any): number | null {
  if (val === null || val === undefined || val === "") return null;
  const n = Number(val);
  return isNaN(n) ? null : n;
}

/**
 * Reads the Excel file and writes a static `data/data.js` file that the
 * standalone HTML viewer loads via a <script> tag.
 *
 * @param excelPath Path to the properties.xlsx file.
 */
export async function exportViewerData(excelPath: string): Promise<void> {
  if (!fs.existsSync(excelPath)) {
    logger.warn(`Viewer export skipped — Excel file not found: ${excelPath}`);
    return;
  }

  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(excelPath);

  const allProperties = await readSheet(workbook, "Propriedades");
  const newProperties = await readSheet(workbook, "Novos");

  // Filter all properties by the configured locations of interest
  // Only apply location filter if FILTER_BY_LOCATION is true
  const filteredProperties = config.filterByLocation
    ? allProperties.filter((p) => isPropertyInLocation(p, config.zoneDistricts))
    : allProperties; // When filtering is disabled, show all properties

  const payload = {
    newProperties,
    allProperties,
    filteredProperties,
    locations: LOCATIONS,
    zoneDistricts: config.zoneDistricts,
    generatedAt: new Date().toISOString(),
  };

  // Write data.js into the viewer/ folder (alongside index.html, app.js, etc.)
  const outputDir = path.join(process.cwd(), "viewer");
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  const outputPath = path.join(outputDir, "data.js");

  // Write as a global variable so the HTML can load it with file:// protocol
  const jsContent =
    `// AUTO-GENERATED by exportViewerData() — do not edit manually.\n` +
    `// Last updated: ${payload.generatedAt}\n` +
    `window.__PROPERTY_DATA__ = ${JSON.stringify(payload, null, 2)};\n`;

  fs.writeFileSync(outputPath, jsContent, "utf-8");

  logger.info(
    `Viewer data exported: ${outputPath} ` +
      `(all: ${allProperties.length}, new: ${newProperties.length}, filtered: ${filteredProperties.length})`
  );
}
